language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11

services:
  - docker

before_install:
  - npm install --global sass postcss-cli autoprefixer
  - go get -d ./...

before_script:
  - export SASS_STYLE=$(if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "compressed"; else echo "expanded"; fi)

script:
  - ./processSass.sh
  - go test -v ./...
